### ISSUE TITLE
Allow use debug bundle in Node.js environment

### ISSUE THREAD

**Issue by alanshaw** [HenrikJoreteg/redux-bundler#31]
```
/Users/alan/Code/project/node_modules/redux-bundler/dist/redux-bundler.js:1891
        self.logSelectors && self.logSelectors();
        ^

ReferenceError: self is not defined
    at /Users/alan/Code/project/node_modules/redux-bundler/dist/redux-bundler.js:1891:9
    at /Users/alan/Code/project/node_modules/redux-bundler/dist/redux-bundler.js:52:16
    at Object.dispatch (/Users/alan/Code/project/node_modules/redux-bundler/dist/redux-bundler.js:37:12)
    at Timeout._onTimeout (/Users/alan/Code/project/node_modules/redux-bundler/dist/redux-bundler.js:1619:27)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

I added `global.self = global` prior to calling `store.doEnableDebug()` and it started working so I think it's a simple fix.

**Comment by HenrikJoreteg** [comment]
just published v25.0.0, it includes a fix for this, thanks! https://github.com/HenrikJoreteg/redux-bundler/blob/master/docs/misc/changelog.md#change-log
